# Cascading LSF Job System Configuration - MEDIUM SCALE
# This configuration tests larger trees with moderate number of instances

# Execution control
execution:
  random_seed: 42  # Master seed for reproducibility
  num_gt_instances: 10  # Test with 10 instances (0-9)
  cas9_simulations_per_gt: 10  # Generate 5 Cas9 simulations per GT for statistics
  parallel_execution: true  # Whether to run jobs in parallel
  run_name: "medium_scale_test"  # Name for this experimental run
  conda_environment: "cas11"  # Conda environment for job execution (default: cas11)
  
# Ground truth generation parameters
ground_truth:
  tree_config:
    N: 150 # Full simulated population: Total number of cells in the original simulated tree 
    n: 100  #  Observed/sampled population: Number of cells actually "sequenced" or analyzed 
    fitness:
      initial_birth_scale: 2
      #fitness_base: 1.1  # or 1.0          # NO fitness advantage (neutral)
      fitness_base: 1.0
      #fitness_std: 0.25  # 0.0
      fitness_std: 0.0
  
  # Seeds for each GT instance (if empty, will auto-generate) 
  instance_seeds: []  # Empty for auto-generation of 13 instances

# Cas9 simulation tiers - each GT will generate 5 simulations per tier
cas9_tiers:
  1:
    name: "Tier 1 - Ultra High Fidelity"
    description: "Near-perfect recording: 100 integrations × 50 sites"
    k: 100  # number of cassettes (integrations)
    cassette_size: 50  # sites per cassette
    m: 50  # unique mutations per site
    mutation_rate_pattern: "exponential_decay"
    base_mutation_rate: 2.0
    state_priors_exponent: 1e-6
    # Missing data controls
    heritable_silencing_rate: 0.0001    # Very low missing data for high fidelity
    stochastic_silencing_rate: 0.005    # Minimal stochastic dropout

  2:
    name: "Tier 2 - High Fidelity"
    description: "Good recording: 50 integrations × 20 sites"
    k: 10
    cassette_size: 10
    m: 20
    mutation_rate_pattern: "uniform"
    base_mutation_rate: 1.2
    state_priors_exponent: 1e-4
    # Missing data controls
    heritable_silencing_rate: 0.001     # Low missing data
    stochastic_silencing_rate: 0.01     # Standard stochastic dropout

  3:
    name: "Tier 3 - High Fidelity II"
    description: "Good recording with slightly more missing data: 50 integrations × 20 sites"
    k: 10
    cassette_size: 10
    m: 20
    mutation_rate_pattern: "uniform"
    base_mutation_rate: 1.2
    state_priors_exponent: 1e-4
    # Missing data controls
    heritable_silencing_rate: 0.0015    # Slightly higher missing data
    stochastic_silencing_rate: 0.015    # Slightly higher stochastic dropout

  4:
    name: "Tier 4 - Medium Fidelity"
    description: "Moderate recording: 20 integrations × 10 sites"
    k: 5
    cassette_size: 3
    m: 20
    mutation_rate_pattern: "uniform"
    base_mutation_rate: 1.0
    state_priors_exponent: 1e-4
    # Missing data controls
    heritable_silencing_rate: 0.005     # Moderate missing data
    stochastic_silencing_rate: 0.02     # Increased stochastic dropout

  5:
    name: "Tier 5 - Medium Fidelity II"
    description: "Moderate recording with higher missing data: 20 integrations × 10 sites"
    k: 5
    cassette_size: 3
    m: 20
    mutation_rate_pattern: "uniform"
    base_mutation_rate: 1.0
    state_priors_exponent: 1e-4
    # Missing data controls
    heritable_silencing_rate: 0.0075    # Higher moderate missing data
    stochastic_silencing_rate: 0.025    # Higher stochastic dropout

  6:
    name: "Tier 6 - Low Fidelity"
    description: "Poor recording: 5 integrations × 3 sites"
    k: 5
    cassette_size: 3
    m: 10
    mutation_rate_pattern: "uniform"
    base_mutation_rate: 0.8
    state_priors_exponent: 1e-3
    # Missing data controls
    heritable_silencing_rate: 0.01      # High missing data for low fidelity
    stochastic_silencing_rate: 0.05     # High stochastic dropout

  7:
    name: "Tier 7 - Low Fidelity II"
    description: "Poor recording with maximum missing data: 5 integrations × 3 sites"
    k: 5
    cassette_size: 3
    m: 10
    mutation_rate_pattern: "uniform"
    base_mutation_rate: 0.8
    state_priors_exponent: 1e-3
    # Missing data controls
    heritable_silencing_rate: 0.02      # Very high missing data for low fidelity
    stochastic_silencing_rate: 0.05     # High stochastic dropout
# Solver configuration
solvers:
  enabled:
    - "nj"
    - "greedy"
    - "spectral"
    - "maxcut"  
    - "smj" 
  
  disabled:
    - "dmj"     # Disabled due to DistanceSolver issues
    - "vanilla"
    - "ilp"
  
  reconstructions_per_solver: 1  # Reconstructions per solver per Cas9 simulation
  
  # Solver-specific parameters
  solver_params:
    nj:
      add_root: true
    maxcut:
      time_limit: 900  # 15 minutes for larger trees
    greedy:
      max_iterations: 3000

# LSF job parameters - FURTHER INCREASED FOR LARGER TREES
lsf:
  queues:
    master_gt: "medium"
    cas9_recording: "medium"
    reconstruction: "long"  # Long queue for big reconstructions

  # Job throttling - control concurrent job submission
  throttling:
    max_concurrent_cas9_jobs: 20      # Max CAS9 recording jobs running at once
    max_concurrent_reconstruction_jobs: 1000  # Max reconstruction jobs running at once
    job_submission_delay: 2.0         # Seconds to wait between job submissions
    batch_size: 50                    # Submit jobs in batches of this size
    check_interval: 60                # Seconds between job count checks

  resources:
    master_gt:
      cores: 25  # More cores for bigger trees
      memory_gb: 1.5  # More memory
      time_limit: "4:00"  # 4 hours
      
    cas9_recording:
      cores: 35
      memory_gb: 1.5
      time_limit: "2:00"  # 2 hours
      
    reconstruction:
      cores: 65
      memory_gb: 1.5  
      time_limit: "6:00"  # 6 hours maximum per reconstruction
      
  # log_dir is now derived from shared_dir/logs - no hardcoded paths

# Output and analysis  
output:
  shared_dir: "oishared_ny"
  save_intermediate_trees: true
  save_detailed_metrics: true
  generate_plots: false
  compare_across_tiers: true
  
  gt_prefix: "gt_medium"  
  cas9_prefix: "cas9_medium"  
  result_prefix: "result_medium"

# Monitoring
monitoring:
  continuous_monitoring: true
  check_interval: 120  # Check every 2 minutes
  max_job_wait_time: 21600  # 6 hours timeout
  
  notifications:
    enabled: false

debug:
  verbose_logging: true
  save_debug_info: true
  test_mode: false
